#!/bin/bash

time=0
while true; do
  newtime=$(find ./src ./test -name "[A-Z]*.hs" -exec stat -f "%m" \{} \; | sort -n -r | head -1)
  if [ "$newtime" -gt "$time" ]; then
    clear
    stack test
  fi

  time=$newtime;
  sleep 1
done
